import { FoodItem } from '../../../types/food';

export const aves: FoodItem[] = [
  {
    id: 'ave_001',
    name: 'Pollo (Pecho)',
    nameTranslations: {
      es: 'Pollo (Pecho)',
      en: 'Chicken (Breast)',
      pt: 'Frango (Peito)'
    },
    description: 'Pechuga de pollo magra, alta en proteína',
    descriptionTranslations: {
      es: 'Pechuga de pollo magra, alta en proteína',
      en: 'Lean chicken breast, high in protein',
      pt: 'Peito de frango magro, rico em proteína'
    },
    brand: 'Generic',
    calories: 165,
    protein: 31.0,
    carbs: 0.0,
    fat: 3.6,
    fiber: 0.0,
    sugar: 0.0,
    sodium: 74,
    servingSize: '100g',
    category: 'carnes',
    subcategory: 'aves',
    tags: ['proteína', 'bajo grasa', 'musculo', 'pollo'],
    tagsTranslations: {
      es: ['proteína', 'bajo grasa', 'musculo', 'pollo'],
      en: ['protein', 'low fat', 'muscle', 'chicken'],
      pt: ['proteína', 'baixo teor de gordura', 'músculo', 'frango']
    },
    isCustom: false
  },
  {
    id: 'ave_002',
    name: 'Pollo (Muslo)',
    nameTranslations: {
      es: 'Pollo (Muslo)',
      en: 'Chicken (Thigh)',
      pt: 'Frango (Coxa)'
    },
    description: 'Muslo de pollo con piel',
    descriptionTranslations: {
      es: 'Muslo de pollo con piel',
      en: 'Chicken thigh with skin',
      pt: 'Coxa de frango com pele'
    },
    brand: 'Generic',
    calories: 209,
    protein: 26.0,
    carbs: 0.0,
    fat: 11.0,
    fiber: 0.0,
    sugar: 0.0,
    sodium: 93,
    servingSize: '100g',
    category: 'carnes',
    subcategory: 'aves',
    tags: ['proteína', 'grasa', 'musculo', 'pollo'],
    tagsTranslations: {
      es: ['proteína', 'grasa', 'musculo', 'pollo'],
      en: ['protein', 'fat', 'muscle', 'chicken'],
      pt: ['proteína', 'gordura', 'músculo', 'frango']
    },
    isCustom: false
  },
  {
    id: 'ave_003',
    name: 'Pavo (Pecho)',
    nameTranslations: {
      es: 'Pavo (Pecho)',
      en: 'Turkey (Breast)',
      pt: 'Peru (Peito)'
    },
    description: 'Pechuga de pavo magra, alta en proteína',
    descriptionTranslations: {
      es: 'Pechuga de pavo magra, alta en proteína',
      en: 'Lean turkey breast, high in protein',
      pt: 'Peito de peru magro, rico em proteína'
    },
    brand: 'Generic',
    calories: 135,
    protein: 29.6,
    carbs: 0.0,
    fat: 1.7,
    fiber: 0.0,
    sugar: 0.0,
    sodium: 103,
    servingSize: '100g',
    category: 'carnes',
    subcategory: 'aves',
    tags: ['proteína', 'bajo grasa', 'selenio', 'pavo'],
    tagsTranslations: {
      es: ['proteína', 'bajo grasa', 'selenio', 'pavo'],
      en: ['protein', 'low fat', 'selenium', 'turkey'],
      pt: ['proteína', 'baixo teor de gordura', 'selênio', 'peru']
    },
    isCustom: false
  },
  {
    id: 'ave_004',
    name: 'Pato',
    description: 'Carne fresca de pato',
    brand: 'Generic',
    calories: 337,
    protein: 19.0,
    carbs: 0.0,
    fat: 28.0,
    fiber: 0.0,
    sugar: 0.0,
    sodium: 63,
    servingSize: '100g',
    category: 'carnes',
    subcategory: 'aves',
    tags: ['proteína', 'grasa', 'hierro', 'pato'],
    isCustom: false
  },
  {
    id: 'ave_005',
    name: 'Pechuga de Pollo (Sin Piel)',
    description: 'Pechuga de pollo sin piel, extra magra',
    brand: 'Generic',
    calories: 110,
    protein: 23.0,
    carbs: 0.0,
    fat: 1.2,
    fiber: 0.0,
    sugar: 0.0,
    sodium: 49,
    servingSize: '100g',
    category: 'carnes',
    subcategory: 'aves',
    tags: ['proteína', 'muy bajo grasa', 'musculo', 'pollo'],
    isCustom: false
  },
  {
    id: 'ave_006',
    name: 'Ala de Pollo',
    description: 'Ala de pollo con piel',
    brand: 'Generic',
    calories: 203,
    protein: 18.3,
    carbs: 0.0,
    fat: 14.0,
    fiber: 0.0,
    sugar: 0.0,
    sodium: 81,
    servingSize: '100g',
    category: 'carnes',
    subcategory: 'aves',
    tags: ['proteína', 'grasa', 'pollo', 'ala'],
    isCustom: false
  },
  {
    id: 'ave_007',
    name: 'Codorniz',
    description: 'Carne de codorniz pequeña',
    brand: 'Generic',
    calories: 192,
    protein: 25.0,
    carbs: 0.0,
    fat: 9.0,
    fiber: 0.0,
    sugar: 0.0,
    sodium: 53,
    servingSize: '100g',
    category: 'carnes',
    subcategory: 'aves',
    tags: ['proteína', 'pequeña', 'codorniz', 'ave'],
    isCustom: false
  },
  {
    id: 'ave_008',
    name: 'Pollo Entero',
    description: 'Pollo entero con piel',
    brand: 'Generic',
    calories: 239,
    protein: 27.0,
    carbs: 0.0,
    fat: 14.0,
    fiber: 0.0,
    sugar: 0.0,
    sodium: 82,
    servingSize: '100g',
    category: 'carnes',
    subcategory: 'aves',
    tags: ['proteína', 'grasa', 'pollo', 'entero'],
    isCustom: false
  },
  {
    id: 'ave_009',
    name: 'Pechuga de Pollo Orgánica',
    description: 'Pechuga de pollo orgánica sin hormonas',
    brand: 'Generic',
    calories: 110,
    protein: 23.0,
    carbs: 0.0,
    fat: 1.2,
    fiber: 0.0,
    sugar: 0.0,
    sodium: 49,
    servingSize: '100g',
    category: 'carnes',
    subcategory: 'aves',
    tags: ['proteína', 'orgánico', 'sin hormonas', 'pollo'],
    isCustom: false
  },
  {
    id: 'ave_010',
    name: 'Muslo de Pollo Sin Piel',
    description: 'Muslo de pollo sin piel, más magro',
    brand: 'Generic',
    calories: 172,
    protein: 26.0,
    carbs: 0.0,
    fat: 7.0,
    fiber: 0.0,
    sugar: 0.0,
    sodium: 93,
    servingSize: '100g',
    category: 'carnes',
    subcategory: 'aves',
    tags: ['proteína', 'bajo grasa', 'musculo', 'pollo'],
    isCustom: false
  },
  {
    id: 'ave_011',
    name: 'Ala de Pollo Sin Piel',
    description: 'Ala de pollo sin piel',
    brand: 'Generic',
    calories: 172,
    protein: 26.0,
    carbs: 0.0,
    fat: 7.0,
    fiber: 0.0,
    sugar: 0.0,
    sodium: 81,
    servingSize: '100g',
    category: 'carnes',
    subcategory: 'aves',
    tags: ['proteína', 'bajo grasa', 'pollo', 'ala'],
    isCustom: false
  },
  {
    id: 'ave_012',
    name: 'Pechuga de Pavo Orgánica',
    description: 'Pechuga de pavo orgánica sin hormonas',
    brand: 'Generic',
    calories: 135,
    protein: 29.6,
    carbs: 0.0,
    fat: 1.7,
    fiber: 0.0,
    sugar: 0.0,
    sodium: 103,
    servingSize: '100g',
    category: 'carnes',
    subcategory: 'aves',
    tags: ['proteína', 'orgánico', 'selenio', 'pavo'],
    isCustom: false
  },
  {
    id: 'ave_013',
    name: 'Muslo de Pavo',
    description: 'Muslo de pavo con piel',
    brand: 'Generic',
    calories: 189,
    protein: 25.0,
    carbs: 0.0,
    fat: 9.0,
    fiber: 0.0,
    sugar: 0.0,
    sodium: 103,
    servingSize: '100g',
    category: 'carnes',
    subcategory: 'aves',
    tags: ['proteína', 'grasa', 'musculo', 'pavo'],
    isCustom: false
  },
  {
    id: 'ave_014',
    name: 'Pechuga de Pato Sin Piel',
    description: 'Pechuga de pato sin piel, más magra',
    brand: 'Generic',
    calories: 201,
    protein: 23.0,
    carbs: 0.0,
    fat: 12.0,
    fiber: 0.0,
    sugar: 0.0,
    sodium: 63,
    servingSize: '100g',
    category: 'carnes',
    subcategory: 'aves',
    tags: ['proteína', 'hierro', 'pato', 'magro'],
    isCustom: false
  },
  {
    id: 'ave_015',
    name: 'Muslo de Pato',
    description: 'Muslo de pato con piel',
    brand: 'Generic',
    calories: 337,
    protein: 19.0,
    carbs: 0.0,
    fat: 28.0,
    fiber: 0.0,
    sugar: 0.0,
    sodium: 63,
    servingSize: '100g',
    category: 'carnes',
    subcategory: 'aves',
    tags: ['proteína', 'grasa', 'hierro', 'pato'],
    isCustom: false
  },
  {
    id: 'ave_016',
    name: 'Pechuga de Codorniz',
    description: 'Pechuga de codorniz pequeña',
    brand: 'Generic',
    calories: 192,
    protein: 25.0,
    carbs: 0.0,
    fat: 9.0,
    fiber: 0.0,
    sugar: 0.0,
    sodium: 53,
    servingSize: '100g',
    category: 'carnes',
    subcategory: 'aves',
    tags: ['proteína', 'pequeña', 'codorniz', 'ave'],
    isCustom: false
  },
  {
    id: 'ave_017',
    name: 'Pechuga de Faisán',
    description: 'Pechuga de faisán silvestre',
    brand: 'Generic',
    calories: 181,
    protein: 25.0,
    carbs: 0.0,
    fat: 8.0,
    fiber: 0.0,
    sugar: 0.0,
    sodium: 53,
    servingSize: '100g',
    category: 'carnes',
    subcategory: 'aves',
    tags: ['proteína', 'silvestre', 'faisán', 'ave'],
    isCustom: false
  }
];
